### ISSUE TITLE
does not work when applied to my component using angular 4 

### ISSUE THREAD

**Issue by donacoba090909** [joselcvarela/ng2-carouselamos#1]
Hi support,
 need your assistance how to implement to my component angular

I installed to npm i ng2-carouselamos --save and import to my module.ts
I copy paste the code but does not work when clicking the next and prev image 
<div
  ng2-carouselamos
  [width]="500"
  [items]="listOfItems"
  [$item]="itemTemplate"
  [$prev]="prevTemplate"
  [$next]="nextTemplate"
></div>

<ng-template #prevTemplate>
  <img src="prev.png" />
</ng-template>
<ng-template #nextTemplate>
  <img src="next.png" />
</ng-template>
<ng-template let-item let-i="index" #itemTemplate>
  {{i}}. {{item.name}}
</ng-template>

do we need to import the  Ng2CarouselamosModule to the components or any directive to import?

**Comment by joselcvarela** [comment]
Hey @donacoba090909 
Try to add this inside #itemTemplate
```html
<div style="min-width: 200px">
  <p>{{i}} - {{item.name}}</p>
</div>
```

**Comment by donacoba090909** [comment]
fantastic. it's working now. thanks a lot.

**Comment by joselcvarela** [comment]
You're welcome ;)
Closing...
