### ISSUE TITLE
Disable dragging

### ISSUE THREAD

**Issue by ch-hristov** [joselcvarela/ng2-carouselamos#17]
Whenever I drag the carousel item it attempts to scroll the whole carousel. Is there a way to disable this behavior?

**Comment by joselcvarela** [comment]
Hey @ch-hristov ,
I think the fastest way you can achieve what you want is to create a new component, extend this module to component and then override the mouse and touch methods with return null, like so:
`onMousedown = onTouchdown = onMousemove = onTouchmove = onMouseup = onTouchup = () => return null`

**Comment by ch-hristov** [comment]
Hi, sorry to ask you again but I'm quite clueless on how to extend it in a way that doesn't involve me copying the template of your component. 
Googling extending components yields me normal inheritance but always includes the template itself.
