### ISSUE TITLE
Get the current active item and display as preview

### ISSUE THREAD

**Issue by lexcaraig** [joselcvarela/ng2-carouselamos#2]
Hi guys! How do you access the current active item? Like for e.g your current item is at the center and you want to display it outside the scope like for e.g.

```
[{ 
cover: string, 
name: string, 
preview: string 
}]

<div>
  <div>
    <!-- is it possible to put the item.preview here?
        It is outside of *ngFor
    -->
  </div>
  <div *ngFor="let item of items">
      <img [src]="item.cover" alt="item.name">
  </div>
</div>
```

Thanks a lot!

**Comment by joselcvarela** [comment]
Hey @lexcaraig, I will work on this very soon and get you updated ;)

**Comment by lexcaraig** [comment]
I'm looking forward to this. It'll be a big help to everybody. Thanks a lot man! :)

**Comment by joselcvarela** [comment]
@lexcaraig I just updated the package (what a coincidence). I added a let-selectedIndex to the template so you have the index of the first visible element (check the readme). Tell me if this fits what you expected so I can close the issue ;)

**Comment by lexcaraig** [comment]
@joselcvarela yeah, i just saw it. But Could you help me a little more? I can't implement it. Am I missing something? Thanks again!

```
<div class="ui-angular-carouselamos__section">
  <ng-container *ngTemplateOutlet="preview"></ng-container>
  <div
    ng2-carouselamos
    [width]="500"
    [items]="listOfItems"
    [$item]="itemTemplate"
    [$prev]="prevTemplate"
    [$next]="nextTemplate">
  </div>

  <ng-template #prevTemplate>
    prev
  </ng-template>

  <ng-template #nextTemplate>
    next
  </ng-template>

  <ng-template let-item let-i="index" let-selectedIndex="selectedIndex" #itemTemplate>
    <ng-template #preview> {{item.preview}} </ng-template>
    <div style="min-width: 200px">
      <b *ngIf="i === selectedIndex">{{i}}. {{item.name}}</b>
      <span *ngIf="i !== selectedIndex">{{i}}. {{item.name}}</span>
    </div>
  </ng-template>

</div>
```

**Comment by joselcvarela** [comment]
@lexcaraig sorry about that, but I realize that what you want can't be achieved by this way. So I changed the code (but the selectedIndex still works inside template) to be possible get the selected item/index outside the ngFor template. So add the event handler (onSelectedItem) where you put the ng2-carouselamos attribute and you can achieve what you desired, I guess. Check the README for further information

**Comment by lexcaraig** [comment]
Yeah man! Thanks! But I think i found some issue. But let me ask you it first. Is it possible to get the current selectedIndex on init of the component?

This works pretty well as your docs said.

```
<div
    ng2-carouselamos
    [width]="500"
    [items]="listOfItems"
    [$item]="itemTemplate"
    [$prev]="prevTemplate"
    [$next]="nextTemplate"
    (onSelectedItem)="selectedItem = $event.item; selectedIndex = $event.index">
  </div>

  <span>{{ selectedItem?.preview | json }}</span>
```

**Comment by lexcaraig** [comment]
Or atleast let us have the access of the properties of the component so we can decide wether to initialize it onInit of afterViewInit. Would that make sense?

**Comment by joselcvarela** [comment]
Hi @lexcaraig,
It's been a while, but I've been busy.
I created this PR #13 that should implement what you desired. Can you have a look? 
Thanks

**Comment by lexcaraig** [comment]
This is so great! Thanks a lot! Really appreciate it! :)

**Comment by joselcvarela** [comment]
Hey @lexcaraig,
I just publish a new version. You can check the tag here: [3.2.0](https://github.com/joselcvarela/ng2-carouselamos/tree/v3.2.0)
