### ISSUE TITLE
Set index of initial item

### ISSUE THREAD

**Issue by AdkaJ** [joselcvarela/ng2-carouselamos#25]
Hi guys,
I would like to ask if there is a way to set up index of "initialSlide"? E.g. if I have a list of 10items and I see 3 of them then by setting ititialSlide = 3 I wanna see slides with index 2,3,4.
Is there a way to set this behaviour?
Many thanks.

**Comment by ginamako** [comment]
i would very much be interested in the same feature as well

**Comment by anup0651** [comment]
Hi,
     is there any way to display on slider last data of the  Array ? For example if we have array[1,2,3,4.....11,12].
Then i want to display last 3 values on slider like 10,11,12.
Thanks in Advance.

**Comment by badrinath389** [comment]
Hi,
 I am also waiting for this changes. 

Thanks.

**Comment by joselcvarela** [comment]
Hey guys,
Sorry for the late response but here I am with this feature you have been waiting for so long :)
Check here #32
It is also published under `ng2-carouselamos@4.1.0` version

**Comment by anup0651** [comment]
Thank you so much
