### ISSUE TITLE
(click) on items doesn't trigger on mobile

### ISSUE THREAD

**Issue by Tibo46** [joselcvarela/ng2-carouselamos#26]
Hello,

I've setup a carousel with:
`<ng-template #item let-item let-i="index">
     <div class="items" (click)="popupImage($event, i)">
          <img class="thumb" src="{{ item.name }}">
     </div>
</ng-template>`
my `popupImage($event, i)` is triggered on desktop but never not on Chrome android, and trigger for first and last item in Safari Iphone.

Anyone could help me with that?

**Comment by rohith080889** [comment]
same issue here, did you find any solution yet ?

**Comment by joselcvarela** [comment]
@Tibo46, @rohith080889  sorry for the late response but this problem is not related to this module.
You are listening to `click` event and click events doesn't work on touch devices. 
I am closing this but feel free to reopening it if you think it worth.
